version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: flowwave
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build: .
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=mongodb://mongo:27017/flowwave
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - ./:/app

volumes:
  mongo-data:
