import React, { useState, useEffect } from 'react';

const VirtualAccountDisplay = ({ 
  transaction, 
  onPaymentConfirmed,
  className = '' 
}) => {
  const [virtualAccount, setVirtualAccount] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    // Extract virtual account from transaction meta (generated by backend)
    if (transaction && transaction.meta && !virtualAccount) {
      const accountData = {
        accountNumber: transaction.meta.virtualAccountNumber,
        bankName: transaction.meta.virtualBankName,
        accountName: transaction.meta.virtualAccountName || `${transaction.beneficiary?.beneficiaryName || 'Flowwave User'} - Temp Account`,
        reference: transaction.referenceId || `FW${Date.now().toString().slice(-8)}`,
        expiryTime: transaction.meta.expiryTime || new Date(Date.now() + 30 * 60 * 1000).toLocaleTimeString(),
        provider: transaction.meta.virtualAccountProvider || 'Flowwave Payment Systems',
        paymentInstructions: transaction.meta.paymentInstructions,
        paystackCustomerCode: transaction.meta.paystackCustomerCode
      };
      
      setVirtualAccount(accountData);
      console.log('📋 Virtual account from transaction meta:', accountData);
      console.log('📋 Full transaction data:', transaction);
    }
  }, [transaction]);

  const handleCopyAccountNumber = () => {
    if (virtualAccount?.accountNumber) {
      navigator.clipboard.writeText(virtualAccount.accountNumber);
      // You could add a toast notification here
    }
  };

  // Show loading state if no transaction data yet
  if (!transaction) {
    return (
      <div className={`bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden ${className}`}>
        <div className="p-6 flex flex-col items-center justify-center py-12">
          <div className="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4"></div>
          <p className="text-gray-600 dark:text-gray-300 text-center">
            Loading payment instructions...
          </p>
        </div>
      </div>
    );
  }

  // Show error if no virtual account in transaction meta
  if (!virtualAccount && transaction) {
    return (
      <div className={`bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden ${className}`}>
        <div className="bg-gradient-to-r from-orange-600 to-orange-700 p-6">
          <h3 className="text-xl font-bold text-white mb-2">
            Transaction Pending
          </h3>
          <p className="text-orange-100">
            Please complete the transaction to generate virtual account
          </p>
        </div>
        <div className="p-6">
          <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 rounded-lg p-4">
            <p className="text-orange-700 dark:text-orange-300 text-center">
              Virtual account will be generated when transaction is initiated
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden ${className}`}>
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-600 p-6">
        <h3 className="text-xl font-bold text-white mb-2">
          Payment Instructions
        </h3>
        <p className="text-blue-100">
          Transfer the total amount to the virtual account below
        </p>
      </div>

      {/* Account Details */}
      <div className="p-6 space-y-6">
        {/* Amount and Reference */}
        <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-300 mb-1">
                Amount to Pay:
              </p>
              <p className="text-2xl font-bold text-gray-800 dark:text-white">
                {transaction.currency} {transaction.total}
              </p>
            </div>
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-300 mb-1">
                Reference:
              </p>
              <p className="text-lg font-mono font-semibold text-gray-800 dark:text-white">
                {transaction.referenceId}
              </p>
            </div>
          </div>
        </div>

        {/* Virtual Account Info */}
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Bank Name:
            </label>
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-blue-100 dark:bg-blue-900/30 rounded-full flex items-center justify-center">
                <svg className="w-6 h-6 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                </svg>
              </div>
              <span className="text-lg font-semibold text-gray-800 dark:text-white">
                {virtualAccount.bankName}
              </span>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Account Number:
            </label>
            <div className="flex items-center space-x-3">
              <div className="flex-1 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg px-4 py-3">
                <span className="text-xl font-mono font-bold text-gray-800 dark:text-white">
                  {virtualAccount.accountNumber}
                </span>
              </div>
              <button
                onClick={handleCopyAccountNumber}
                className="p-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors"
                title="Copy account number"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
              </button>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Account Name:
            </label>
            <div className="flex-1 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg px-4 py-3">
              <span className="text-lg font-semibold text-gray-800 dark:text-white">
                {virtualAccount.accountName}
              </span>
            </div>
          </div>

          {virtualAccount.expiryTime && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Account Expires:
              </label>
              <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 rounded-lg px-4 py-3">
                <span className="text-orange-700 dark:text-orange-300 font-medium">
                  {virtualAccount.expiryTime}
                </span>
              </div>
            </div>
          )}

          {virtualAccount.paystackCustomerCode && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Customer Code:
              </label>
              <div className="bg-purple-50 dark:bg-purple-900/20 border border-purple-200 dark:border-purple-800 rounded-lg px-4 py-3">
                <span className="text-purple-700 dark:text-purple-300 font-mono font-medium">
                  {virtualAccount.paystackCustomerCode}
                </span>
              </div>
            </div>
          )}

          {/* Beneficiary Information */}
          {(transaction.beneficiary || transaction.recipient) && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Beneficiary Details:
              </label>
              <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg px-4 py-3">
                <div className="space-y-1">
                  <p className="text-green-700 dark:text-green-300 font-medium">
                    {transaction.beneficiary?.beneficiaryName || transaction.recipient?.fullName || 'Beneficiary'}
                  </p>
                  <p className="text-green-600 dark:text-green-400 text-sm">
                    {transaction.beneficiary?.beneficiaryBank || transaction.recipient?.bankName || 'Bank'}
                  </p>
                  <p className="text-green-600 dark:text-green-400 text-sm font-mono">
                    {transaction.beneficiary?.beneficiaryAccountNumber || transaction.recipient?.accountNumber || 'Account Number'}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* If no beneficiary info, show a placeholder */}
          {!transaction.beneficiary && !transaction.recipient && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Beneficiary Details:
              </label>
              <div className="bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg px-4 py-3">
                <p className="text-gray-500 dark:text-gray-400 text-sm">
                  Beneficiary information will be displayed here
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Payment Instructions */}
        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
          <h4 className="font-semibold text-blue-800 dark:text-blue-200 mb-2">
            Payment Instructions:
          </h4>
          <p className="text-blue-700 dark:text-blue-300 text-sm mb-3">
            {virtualAccount.paymentInstructions}
          </p>
          <div className="text-blue-600 dark:text-blue-400 text-xs">
            <strong>Important:</strong> Transfer the exact amount ({transaction.currency} {transaction.total}) to the virtual account above. 
            Include the reference ID ({transaction.referenceId}) in your transfer description.
            This is a real bank account provided by {virtualAccount.provider} and your payment will be processed automatically.
          </div>
        </div>

        {/* Important Notes */}
        <div className="space-y-2 text-sm text-gray-600 dark:text-gray-300">
          <div className="flex items-start space-x-2">
            <svg className="w-5 h-5 text-yellow-500 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
            </svg>
            <p>
              <strong>Important:</strong> Use the exact amount (${transaction.total}) and include the reference ID ({transaction.referenceId}) in your transfer description.
            </p>
          </div>
          <div className="flex items-start space-x-2">
            <svg className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
            </svg>
            <p>
              This is a real bank account. Your transfer will be processed automatically.
            </p>
          </div>
        </div>

        {/* Action Button */}
        <div className="pt-4 border-t border-gray-200 dark:border-gray-600">
          <button
            onClick={onPaymentConfirmed}
            className="w-full bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 text-white font-semibold py-4 px-6 rounded-lg transition-all duration-300 transform hover:scale-[1.02]"
          >
            I Have Made the Payment
          </button>
        </div>
      </div>
    </div>
  );
};

export default VirtualAccountDisplay;
